name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./docfx
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      shell: pwsh
      run: |
        ./build.ps1 -NoKill
        if (!$?) {Throw "The script has failed." }
